In [6]:
import polars as pl

annot_path = '../references/human_ref/gencode.v49.annotation.gtf'
only_protein_coding = False

annot_df = pl.scan_csv(
    annot_path, separator='\t', comment_prefix='#', has_header=False,
    new_columns=['chr', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attr']
)

# count transcripts per gene
transcript_query = (
    annot_df
    .select(['feature', 'attr'])
    .filter(pl.col('feature') == 'transcript')
    .filter(pl.col('attr').str.contains('gene_type "protein_coding";') if only_protein_coding else pl.lit(True))
    .with_columns(pl.col('attr').str.extract(r'gene_id "([^"]+)";').alias('gene_id'))
    .select(
        pl.col('gene_id').unique(maintain_order=True),
        pl.col('gene_id').unique_counts().alias('transcript_count')
    )
    .filter(
        pl.col('transcript_count') >= 3,
        pl.col('transcript_count') <= 20
    )
)
sample_gene_pool = transcript_query.collect()
all_genes = sample_gene_pool['gene_id'].to_list()

gene_query = (
    annot_df
    .filter(pl.col('feature') == 'gene')
    .with_columns(pl.col('attr').str.extract(r'gene_id "([^"]+)";').alias('gene_id'))
    .filter(pl.col('gene_id').is_in(all_genes))
    .with_columns((pl.col('end') - pl.col('start') + 1).alias('gene_length'))
)
gene_df = gene_query.collect()
gene_df

shape: (22_139, 11)
┌──────┬────────┬─────────┬──────────┬───┬───────┬─────────────────┬─────────────────┬─────────────┐
│ chr  ┆ source ┆ feature ┆ start    ┆ … ┆ frame ┆ attr            ┆ gene_id         ┆ gene_length │
│ ---  ┆ ---    ┆ ---     ┆ ---      ┆   ┆ ---   ┆ ---             ┆ ---             ┆ ---         │
│ str  ┆ str    ┆ str     ┆ i64      ┆   ┆ str   ┆ str             ┆ str             ┆ i64         │
╞══════╪════════╪═════════╪══════════╪═══╪═══════╪═════════════════╪═════════════════╪═════════════╡
│ chr1 ┆ HAVANA ┆ gene    ┆ 28589    ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000243485 ┆ 2521        │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000243485.6";   ┆ .6              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chr1 ┆ HAVANA ┆ gene    ┆ 34553    ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000237613 ┆ 3043        │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000237613.3";   ┆ .3              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chr1 ┆ HAVANA ┆ gene    ┆ 96638    ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000308314 ┆ 9105        │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000308314.1";   ┆ .1              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chr1 ┆ HAVANA ┆ gene    ┆ 257864   ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000292994 ┆ 101818      │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000292994.2";   ┆ .2              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chr1 ┆ HAVANA ┆ gene    ┆ 266753   ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000286448 ┆ 17539       │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000286448.2";   ┆ .2              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ …    ┆ …      ┆ …       ┆ …        ┆ … ┆ …     ┆ …               ┆ …               ┆ …           │
│ chrY ┆ HAVANA ┆ gene    ┆ 56919422 ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000310550 ┆ 34748       │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000310550.1";   ┆ .1              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chrY ┆ HAVANA ┆ gene    ┆ 57067747 ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000292366 ┆ 62543       │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000292366.2";   ┆ .2              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chrY ┆ HAVANA ┆ gene    ┆ 57184216 ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000292373 ┆ 15322       │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000292373.3";   ┆ .3              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chrY ┆ HAVANA ┆ gene    ┆ 57207346 ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000292372 ┆ 4885        │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000292372.1";   ┆ .1              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
│ chrY ┆ HAVANA ┆ gene    ┆ 57208516 ┆ … ┆ .     ┆ gene_id "ENSG00 ┆ ENSG00000310542 ┆ 7119        │
│      ┆        ┆         ┆          ┆   ┆       ┆ 000310542.1";   ┆ .1              ┆             │
│      ┆        ┆         ┆          ┆   ┆       ┆ g…              ┆                 ┆             │
└──────┴────────┴─────────┴──────────┴───┴───────┴─────────────────┴─────────────────┴─────────────┘

In [2]:
sample_query = (
    annot_df
    .filter(
        pl.col('attr').str.contains_any(sample_gene_id)
    )
)
sample_df = sample_query.collect()
sample_df

shape: (3_852, 9)
┌──────┬────────┬────────────┬───────────┬───┬───────┬────────┬───────┬────────────────────────────┐
│ chr  ┆ source ┆ feature    ┆ start     ┆ … ┆ score ┆ strand ┆ frame ┆ attr                       │
│ ---  ┆ ---    ┆ ---        ┆ ---       ┆   ┆ ---   ┆ ---    ┆ ---   ┆ ---                        │
│ str  ┆ str    ┆ str        ┆ i64       ┆   ┆ str   ┆ str    ┆ str   ┆ str                        │
╞══════╪════════╪════════════╪═══════════╪═══╪═══════╪════════╪═══════╪════════════════════════════╡
│ chr1 ┆ HAVANA ┆ gene       ┆ 157745733 ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000132704.17"; …    │
│ chr1 ┆ HAVANA ┆ transcript ┆ 157745733 ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000132704.17"; …    │
│ chr1 ┆ HAVANA ┆ exon       ┆ 157767231 ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000132704.17"; …    │
│ chr1 ┆ HAVANA ┆ exon       ┆ 157766855 ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000132704.17"; …    │
│ chr1 ┆ HAVANA ┆ exon       ┆ 157749650 ┆ … ┆ .     ┆ -      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000132704.17"; …    │
│ …    ┆ …      ┆ …          ┆ …         ┆ … ┆ …     ┆ …      ┆ …     ┆ …                          │
│ chrX ┆ HAVANA ┆ CDS        ┆ 74525750  ┆ … ┆ .     ┆ +      ┆ 0     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000147100.12"; …    │
│ chrX ┆ HAVANA ┆ exon       ┆ 74531333  ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000147100.12"; …    │
│ chrX ┆ HAVANA ┆ CDS        ┆ 74531333  ┆ … ┆ .     ┆ +      ┆ 0     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000147100.12"; …    │
│ chrX ┆ HAVANA ┆ stop_codon ┆ 74531408  ┆ … ┆ .     ┆ +      ┆ 0     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000147100.12"; …    │
│ chrX ┆ HAVANA ┆ UTR        ┆ 74531408  ┆ … ┆ .     ┆ +      ┆ .     ┆ gene_id                    │
│      ┆        ┆            ┆           ┆   ┆       ┆        ┆       ┆ "ENSG00000147100.12"; …    │
└──────┴────────┴────────────┴───────────┴───┴───────┴────────┴───────┴────────────────────────────┘

In [8]:
genes = (
    sample_df
    .filter(pl.col('feature') == 'gene')
    .with_columns((pl.col('end') - pl.col('start')).alias('length'))
)
print(genes.select('length', pl.sum('length').alias('total_length')))

shape: (20, 2)
┌────────┬──────────────┐
│ length ┆ total_length │
│ ---    ┆ ---          │
│ i64    ┆ i64          │
╞════════╪══════════════╡
│ 31536  ┆ 1215405      │
│ 10623  ┆ 1215405      │
│ 28778  ┆ 1215405      │
│ 7370   ┆ 1215405      │
│ 80298  ┆ 1215405      │
│ …      ┆ …            │
│ 25227  ┆ 1215405      │
│ 18838  ┆ 1215405      │
│ 14275  ┆ 1215405      │
│ 6704   ┆ 1215405      │
│ 112535 ┆ 1215405      │
└────────┴──────────────┘